name: deepspeech
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - ipython
  - sox
  - jupyterlab
  - black
  - nltk
  - seaborn
  - pip
  - pip:
    - deepspeech-gpu==0.7.0
    - pydub
    - simpleaudio
    - sox
